# Generated by Django 2.2.6 on 2020-03-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_product_flagcolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='flagcolor',
            new_name='flagbackcolor',
        ),
    ]
