# Generated by Django 2.2.6 on 2020-03-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_aboutus_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.TextField(blank=True),
        ),
    ]
