# Generated by Django 2.2.6 on 2020-03-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_product_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
