# Generated by Django 2.2.6 on 2020-03-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_product_min_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=100, null=True),
        ),
    ]
